---
title: "Lecture 2: Git Basics"
author: "Andy Hoegh"
date: "1/8/2019"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Git Resources

- Git will feel foreign for a while, but you will get a lot of practice in this class

- A great resource, from which I've heavily borrowed is Jenny Bryan's [Happy Git and GitHub for the useR](https://happygitwithr.com)

- Another good reference is the [GitHub Git Cheat Sheet](https://education.github.com/git-cheat-sheet-education.pdf)

## Git: The What and the Why
- Git is a version control system that manages as set of files as a repository, or a *repo*.

- For the long version of why, see [Excuse me, do you have a moment to talk about version control?](https://peerj.com/preprints/3159/)

- For today, just know:
    - Programming expertise, and skills like this, are essential in Data Science
    - Version control will save back up files, in case of computer problems
    - It is an efficient way to handle collaboration
    - Creating R packages is easy with R Studio and github
    - Github pages allows you to create and host website free, such as the course webpage.

## Demo Overview:

I acknowledge that everyone will work at different speeds today, so feel free to work ahead.

1. Github account
2. Upgrade R and R Studio
3. Git installation and initialization
4. Git GUI??
5. Git - to - Github with R Studio
6. Basic Git Commands


## Github Account

- At this point you should have registered for a github account.

- If not, visit [github.com](https://www.github.com) to set up your account.

- If you have an account, go ahead and log in. We will use this soon.

## R and R Studio Updates

- R is currently on version 3.5.2, if your version is much older than this, you will want to update it [here](https://cloud.r-project.org).

- Updating R can be a bit painful, but keeping current is good practice.

- R Studio is constantly adding improvements and updates, including a git interface.

- To stay current, consider using the [Preview version](https://www.rstudio.com/products/rstudio/download/preview/) and updating every month or so.

## Git installation and Git initialization

- If you are lucky, git is already installed on your computer.

- To check you have git, open the terminal or command line, and type `git --version`. In newer versions of R Studio there is a command line tab.

- If `git --version` does not return an error, then you are in luck. Otherwise, git needs to be be [installed](https://happygitwithr.com/install-git.html).

- If you have not already done so we need to initialize git with the following commands in the terminal:
```
git config --global user.name 'First Last'
git config --global user.email 'who@montana.edu'
```
Note the email should correspond to the one you used to sign up for github.

## Git GUI?

- If you are leery of using the command line, consider downloading a git GUI.

- Two options are options are:
    - [gitkraken](https://www.gitkraken.com) and
    - [github desktop](https://desktop.github.com)
    
- Also, know that R Studio has some built in features that simplify the git process too.

## Git - to - Github with R Studio

- Our goal is to work locally, in R Studio, and *push* updates to github.

- First, go to your github page and create a new repo. To do this, 
    - Repository name: git_demo
    - Description: “practice with git”
    - Select Public
    - YES Initialize this repository with a README.
    - Click: create repository.
    
- Next, we will clone this repo and create an R Studio project associated with it.